POST http://localhost:3000/auth/signup 
Content-Type: application/json

{
    "username": "Ravi Teja",
    "email": "ravi@gmail.com",
    "password": "abcd"
}

###

POST http://localhost:3000/auth/logout
