POST http://localhost:3000/auth/signup 
Content-Type: application/json

{
    "username": "Ravi Teja",
    "email": "ravi@gmail.com",
    "password": "abcd"
}

###

# POST http://localhost:3000/auth/login
# Content-Type: application/json

# {
#     "username": "ravi",
#     "password": "ravi1234"
# }

GET http://localhost:3000/posts/latest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzMWQwNjQ2YS1iOTE3LTRlODItODAwNC1kMGY5YzdkMjUxMDciLCJpYXQiOjE3MzM1NjMzNzYsImV4cCI6MTczMzU2MzQzNn0._HYFp96kGVWCJ7v4RHcrr5JRBjOEmgISPq6MdDJYyW8

