POST http://localhost:3000/auth/signup 
Content-Type: application/json

{
    "username": "Ravi Teja",
    "email": "ravi@gmail.com",
    "password": "abcd"
}

###

# POST http://localhost:3000/auth/login
# Content-Type: application/json

# {
#     "username": "ravi",
#     "password": "ravi1234"
# }

GET http://localhost:3000/images/auth

